cwdiff: added -D and -o

diff --git a/cwdiff b/cwdiff
--- a/cwdiff
+++ b/cwdiff
@@ -3,7 +3,8 @@
 #(C) 2009 C. Junghans
 # junghans@mpip-mainz.mpg.de
 
-#version 0.1  04.08.10 -- initial version
+#version 0.1    04.08.10 -- initial version
+#version 0.1.1, 05.08.10 -- added -D and -o
 
 FAT_GREEN="[32;01m"
 GREEN="[32m"
@@ -21,6 +22,9 @@ diff="no"
 filter="no"
 diff_opts='--new-file --unified --show-c-function --recursive'
 ab="no"
+a2ps=tee
+out=""
+style="wdiff"
 
 color_filter() {
   sed -e "s/\[-/$RED/g" \
@@ -42,22 +46,26 @@ show_help () {
   cat << eof
 This colorized the output of wdiff
 $usage
-ARGS will be given to wdiff (no ARGS = read from stdin)
+ARGS will be given to wdiff
 OPTIONS:
 -f, --filter        Just act as a filter (don't run wdiff internally)
                     ARGS will be given to sed (no ARGS = read from stdin)
 -d, --diff          Preprocess input with diff (useful for dirs)
-                    ARGS will be given to diff (no ARGS = read from stdin)
+                    ARGS will be given to diff
+-D, --diffonly      Just colorize the diff and do NOT run wdiff
+                    (implies --diff, and work with --filter)
     --diffopts XXX  Change opts of diff
                     Default: '$diff_opts'
     --ab            replace trunc by a and b (only work with 2 dirs)
     --no-color      Disable-color
+-o, --output XX.ps  Pipe the output to a2ps (also work with --filter)
 -h, --help          Show this help
 -v, --version       Show version
     --hg            Show last log message for hg (or cvs)
 
-Examples:  ${0##*/} -q
-           ${0##*/}
+Examples:  ${0##*/} -d dir1 dir2
+           ${0##*/} --ab -D dir1 dir2
+	   wdiff file1 file2 | ${0##*/} -f
 
 Send bugs and comment to junghans@mpip-mainz.mpg.de
 eof
@@ -66,8 +74,8 @@ eof
 shopt -s extglob
 while [ "${1#-}" != "$1" ]; do
  if [ "${1#--}" = "$1" ] && [ -n "${1:2}" ]; then
-    #short opt with arguments here: fc
-    if [ "${1#-[fc]}" != "${1}" ]; then
+    #short opt with arguments here: o
+    if [ "${1#-[o]}" != "${1}" ]; then
        set -- "${1:0:2}" "${1:2}" "${@:2}"
     else
        set -- "${1:0:2}" "-${1:2}" "${@:2}"
@@ -79,12 +87,22 @@ while [ "${1#-}" != "$1" ]; do
     shift;;
    --no-color)
     unset FAT_GREEN GREEN FAT_RED RED MAG OFF FAT_BLACK
+    color_filter() { sed -e 's/x/x/' "$@";}
     shift;;
    -f | --filter)
     filter="yes"
     shift ;;
    -d | --diff)
     diff="yes"
+    shift ;;
+   -o | --output)
+    [ -z "${2}" ] && die "Missing argument after --output"
+    [ -n "${2%%*.ps}" ] && die "Argument of --output has to end with .ps"
+    out="$2"
+    shift 2;;
+   -D | --diffonly)
+    diff="only"
+    style="udiff"
     shift ;;
    --diffopts)
     diff_opts="$1"
@@ -109,39 +127,53 @@ while [ "${1#-}" != "$1" ]; do
  esac
 done
 
-if [ "$filter" = "yes" ]; then
-  color_filter "$@"
-  exit $?
+if [ -n "$out" ]; then
+  unset FAT_GREEN GREEN FAT_RED RED MAG OFF FAT_BLACK
+  #seem like a bug in the a2ps style file
+  color_filter() { sed -e "s/\[-/[wd-/g" -e "s/-\]/-wd]/g" -e "s/{+/{wd+/g" -e "s/+}/+wd}/g" "$@"; }
+  a2ps=( a2ps -E$style -o "$out" )
 fi
 
-if [ "$diff" = "yes" ]; then
+if [ "$diff" != "no" ]; then
   total_diff=$(mktemp)
   t1=$(mktemp)
   t2=$(mktemp)
-  diff $diff_opts $@ > $total_diff
-  [ $? -eq 2 ] && die
+  if [ "$filter" = "no" ]; then
+    diff $diff_opts "$@" > $total_diff
+    [ $? -eq 2 ] && die
+  else
+    sed -e 's/x/x/' "$@" > $total_diff || die
+  fi
   if [ "$ab" = "yes" ]; then
+    #find the longest equal part in $1 and $2 from the end
     for ((i=1;i<=(${#1}<${#2}?${#1}:${#2});i++)); do
       [ "${1:0-$i}" != "${2:0-$i}" ] && break
     done
     ((i--))
     a="${1:0:${#1}-$i}"
     b="${2:0:${#2}-$i}"
+  else
+    a=a; b=b
   fi
   IFS="$NL"
   for i in $(<$total_diff); do
     [ -z "${i##diff*}" ] && echo -e "$FAT_BLACK${i}$OFF" && continue
-    [ -z "${i##---*}" ] && [ "$ab" = "yes" ] && echo -e "$FAT_RED${i/$a/a}$OFF" && continue
-    [ -z "${i##---*}" ] && echo -e "$FAT_RED${i}$OFF" && continue
-    [ -z "${i##+++*}" ] && [ "$ab" = "yes" ] && echo -e "$FAT_GREEN${i/$b/b}$OFF" && continue
-    [ -z "${i##+++*}" ] && echo -e "$FAT_GREEN${i}$OFF" && continue
+    [ -z "${i##---*}" ] && echo -e "$FAT_RED${i/$a/a}$OFF" && continue
+    [ -z "${i##+++*}" ] && echo -e "$FAT_GREEN${i/$b/b}$OFF" && continue
     [ -z "${i##@@*}" ] && echo -e "$MAG$i$OFF" && continue
-    [ -z "${i##-*}" ] && echo ${i#-} >> $t1 && continue
-    [ -z "${i##+*}" ] && echo ${i#+} >> $t2 && continue
-    wdiff $t1 $t2 | color_filter && : > $t1 && : > $t2
-    echo "${i## }"
-  done
-  exit $?
+    if [ "$diff" = "only" ]; then
+      [ -z "${i##-*}" ] && echo "$RED${i}$OFF" && continue
+      [ -z "${i##+*}" ] && echo "$GREE${i}$OFF"&& continue
+      echo "${i}"
+    else
+      [ -z "${i##-*}" ] && echo ${i#-} >> $t1 && continue
+      [ -z "${i##+*}" ] && echo ${i#+} >> $t2 && continue
+      wdiff $t1 $t2 | color_filter; : > $t1; : > $t2
+      echo "${i## }"
+    fi
+  done | "${a2ps[@]}" 
+elif [ "$filter" = "yes" ]; then
+  color_filter "$@" | "${a2ps[@]}"
+else
+  wdiff $@ | color_filter | "${a2ps[@]}"
 fi
-
-wdiff $@ | color_filter
